apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
  nameResolution:
    component: "sqlite"
    version: "v1"
    configuration:
      connectionString: "file:/tmp/dapr-h-nr.db?_busy_timeout=10000&_journal_mode=WAL"
