apiVersion: apps/v1
kind: Deployment
metadata:
  name: stub-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: stub-agent
  template:
    metadata:
      labels:
        app: stub-agent
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "stub-agent"
        dapr.io/app-port: "8000"
        dapr.io/log-level: "info"
        dapr.io/config: "appconfig"
    spec:
      containers:
        - name: stub-agent
          image: h/stub-agent
          env:
            - name: APP_PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: stub-agent
  namespace: default
spec:
  selector:
    app: stub-agent
  ports:
    - port: 8000
      targetPort: 8000
