apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
  namespace: default
spec:
  policies:
    timeouts:
      agentTimeout: 3600s
  targets:
    apps:
      claude-agent:
        timeout: agentTimeout
      workflow-svc:
        timeout: agentTimeout
