import { describe, expect, it } from "vitest";

import { mcpJsonToCodexToml } from "./codex-mcp-config.ts";

const H_MCP = JSON.stringify({
  mcpServers: {
    workflows: { type: "sse", url: "http://localhost:8005/sse" },
    github: {
      type: "http",
      url: "https://api.githubcopilot.com/mcp/",
      headers: { Authorization: "Bearer ${GH_TOKEN}" },
    },
    dapr: { type: "sse", url: "http://localhost:8011/sse" },
    obs: { type: "sse", url: "http://localhost:8013/sse" },
    notion: {
      type: "stdio",
      command: "npx",
      args: ["-y", "@notionhq/notion-mcp-server"],
      env: { OPENAPI_MCP_HEADERS: '{"Authorization": "Bearer x"}' },
    },
  },
});

describe("mcpJsonToCodexToml", () => {
  it("maps an http server to url + bearer_token_env_var (extracted from the Bearer header)", () => {
    const { toml, included } = mcpJsonToCodexToml(H_MCP);
    expect(included).toContain("github");
    expect(toml).toContain("[mcp_servers.github]");
    expect(toml).toContain('url = "https://api.githubcopilot.com/mcp/"');
    expect(toml).toContain('bearer_token_env_var = "GH_TOKEN"');
  });

  it("maps a stdio server to command + args + env", () => {
    const { toml, included } = mcpJsonToCodexToml(H_MCP);
    expect(included).toContain("notion");
    expect(toml).toContain("[mcp_servers.notion]");
    expect(toml).toContain('command = "npx"');
    expect(toml).toContain('args = ["-y", "@notionhq/notion-mcp-server"]');
    expect(toml).toContain("env = {");
  });

  it("SKIPS sse servers (codex uses streamable-http, not sse) with a reason", () => {
    const { included, skipped } = mcpJsonToCodexToml(H_MCP);
    expect(included).not.toContain("workflows");
    expect(included).not.toContain("dapr");
    expect(included).not.toContain("obs");
    expect(skipped.some((s) => s.startsWith("dapr:") && s.includes("sse"))).toBe(true);
  });

  it("emits a header comment when servers are present", () => {
    expect(mcpJsonToCodexToml(H_MCP).toml).toMatch(/^# Generated by codex-agent/);
  });

  it("returns empty toml (no header) when there are no supported servers", () => {
    const onlySse = JSON.stringify({ mcpServers: { dapr: { type: "sse", url: "http://x/sse" } } });
    const { toml, included } = mcpJsonToCodexToml(onlySse);
    expect(included).toHaveLength(0);
    expect(toml).toBe("");
  });

  it("does not throw on invalid JSON — reports it as skipped", () => {
    const { toml, skipped } = mcpJsonToCodexToml("{not json");
    expect(toml).toBe("");
    expect(skipped[0]).toContain("not valid JSON");
  });

  it("escapes quotes/backslashes in string values", () => {
    const tricky = JSON.stringify({
      mcpServers: { s: { type: "stdio", command: 'a"b\\c' } },
    });
    expect(mcpJsonToCodexToml(tricky).toml).toContain('command = "a\\"b\\\\c"');
  });
});
