// Translate h's MCP config (.mcp.json — the same source claude-agent provisions) into the TOML
// `[mcp_servers.*]` section codex reads from $CODEX_HOME/config.toml. This is codex's parity path
// with claude's mergeMcpConfig: claude auto-discovers a per-cwd `.mcp.json`; codex has only a GLOBAL
// config in CODEX_HOME, so the runner writes a fresh config.toml into a dedicated h-managed
// CODEX_HOME (never the user's ~/.codex) — see the codex gotcha in CLAUDE.md.
//
// Server type mapping (verified against `codex mcp add` output):
//   - http  → Streamable HTTP via [mcp_servers.<name>] url + bearer_token_env_var (extracted from a
//             "Bearer ${VAR}" Authorization header). Includes dapr/obs `/mcp` endpoints; codex
//             reads the env var itself at run time.
//   - stdio → command + args (+ env). Best-effort: codex does NOT expand ${VAR} in env values, so a
//             server whose env needs shell expansion (e.g. notion's OPENAPI_MCP_HEADERS) is emitted
//             as-is and may not authenticate — acceptable, the PR workflows only need `github`.
//   - sse   → SKIPPED: codex's `--url` transport is Streamable HTTP, not legacy SSE, so genuinely
//             SSE-only servers such as workflows can't be consumed. Recorded in `skipped`.

type McpServer = {
  type?: string;
  url?: string;
  headers?: Record<string, string>;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
};
type McpConfig = { mcpServers?: Record<string, McpServer> };

export interface CodexMcpResult {
  /** The `[mcp_servers.*]` TOML to write into $CODEX_HOME/config.toml (empty string if none). */
  toml: string;
  /** Server names emitted. */
  included: string[];
  /** Server names skipped, with the reason (e.g. "obs: sse transport unsupported by codex"). */
  skipped: string[];
}

const tomlString = (s: string): string => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
const tomlArray = (a: string[]): string => `[${a.map(tomlString).join(", ")}]`;
const bearerEnvVar = (auth: string | undefined): string | undefined =>
  auth?.match(/^Bearer\s+\$\{(\w+)\}$/)?.[1];

/**
 * Build the codex `[mcp_servers.*]` config from an h `.mcp.json` string. Pure — value-tested.
 * Never throws on an individual server; a malformed/unsupported one is skipped with a reason.
 */
export function mcpJsonToCodexToml(mcpJson: string): CodexMcpResult {
  let parsed: McpConfig;
  try {
    parsed = JSON.parse(mcpJson) as McpConfig;
  } catch {
    return { toml: "", included: [], skipped: ["<all>: .mcp.json is not valid JSON"] };
  }
  const servers = parsed.mcpServers ?? {};
  const blocks: string[] = [];
  const included: string[] = [];
  const skipped: string[] = [];

  for (const [name, s] of Object.entries(servers)) {
    const type = s.type ?? (s.command ? "stdio" : s.url ? "http" : "unknown");
    if (type === "http") {
      if (!s.url) {
        skipped.push(`${name}: http server has no url`);
        continue;
      }
      const lines = [`[mcp_servers.${name}]`, `url = ${tomlString(s.url)}`];
      const envVar = bearerEnvVar(s.headers?.["Authorization"]);
      if (envVar) lines.push(`bearer_token_env_var = ${tomlString(envVar)}`);
      blocks.push(lines.join("\n"));
      included.push(name);
    } else if (type === "stdio") {
      if (!s.command) {
        skipped.push(`${name}: stdio server has no command`);
        continue;
      }
      const lines = [`[mcp_servers.${name}]`, `command = ${tomlString(s.command)}`];
      if (s.args?.length) lines.push(`args = ${tomlArray(s.args)}`);
      if (s.env && Object.keys(s.env).length) {
        const entries = Object.entries(s.env).map(([k, v]) => `${k} = ${tomlString(v)}`);
        lines.push(`env = { ${entries.join(", ")} }`);
      }
      blocks.push(lines.join("\n"));
      included.push(name);
    } else if (type === "sse") {
      skipped.push(`${name}: sse transport unsupported by codex (needs streamable-http)`);
    } else {
      skipped.push(`${name}: unknown server type`);
    }
  }

  const header =
    "# Generated by codex-agent from h's .mcp.json — do not edit; regenerated each run.\n";
  return {
    toml: blocks.length ? header + blocks.join("\n\n") + "\n" : "",
    included,
    skipped,
  };
}
